# Generated by Django 4.2.5 on 2023-10-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favori',
            new_name='FavoriDb',
        ),
    ]
